### PR TITLE
Unary function change

### LINKED ISSUE #28: saveData throws NAs in train_data
Hi,

I noticed there was a [change](https://github.com/mi-erasmusmc/Explore/commit/7a8a60f9a8d22f94817b55ec0fd735e918f012f9) in `saveData()` compared to the version I was using in tests. If data is TRUE or FALSE, is not converting the data to 0 and 1 like before in [here](https://github.com/mi-erasmusmc/Explore/blob/eb8caee94af372caca22cd212770f2a650793773/R/HelperFunctions.R#L79C3-L81C142).

``` r
train_data <- data.frame(check.names = FALSE,
                          outcomeCount = c(FALSE,FALSE,FALSE,
                                           FALSE,FALSE,TRUE),
                           `198124209` = c(FALSE,FALSE,FALSE,
                                           FALSE,FALSE,TRUE),
                           `316139209` = c(FALSE,FALSE,FALSE,
                                           FALSE,FALSE,FALSE),
                           `316139210` = c(FALSE,FALSE,FALSE,
                                           FALSE,FALSE,FALSE)
                        )

binary_cols <- sapply(1:ncol(train_data), function(c) all(train_data[[c]] %in% 0:1))
train_data[binary_cols] <- lapply(colnames(train_data[binary_cols]), function(c) factor(train_data[[c]], levels=c("0","1"), labels=c(0,1)))
  
print(train_data[binary_cols])
#>   outcomeCount 198124209 316139209 316139210
#> 1         <NA>      <NA>      <NA>      <NA>
#> 2         <NA>      <NA>      <NA>      <NA>
#> 3         <NA>      <NA>      <NA>      <NA>
#> 4         <NA>      <NA>      <NA>      <NA>
#> 5         <NA>      <NA>      <NA>      <NA>
#> 6         <NA>      <NA>      <NA>      <NA>
```

Maybe something like to account for TRUE and FALSE?

``` r
train_data <- data.frame(check.names = FALSE,
                         outcomeCount = c(FALSE,FALSE,FALSE,
                                          FALSE,FALSE,TRUE),
                         `198124209` = c(FALSE,FALSE,FALSE,
                                         FALSE,FALSE,TRUE),
                         `316139209` = c(FALSE,FALSE,FALSE,
                                         FALSE,FALSE,FALSE),
                         `316139210` = c(FALSE,FALSE,FALSE,
                                         FALSE,FALSE,FALSE)
)

binary_cols <- sapply(train_data, function(col) all(col %in% c(0, 1, TRUE, FALSE)))

# Convert TRUE/FALSE to 1/0 and create factors
train_data[binary_cols] <- lapply(train_data[binary_cols], function(col) {
  col <- as.numeric(as.logical(col))  # Convert TRUE/FALSE to 1/0
  factor(col, levels = c(0, 1), labels = c(0, 1))  # Convert to factors
})

print(train_data[binary_cols])
#>   outcomeCount 198124209 316139209 316139210
#> 1            0         0         0         0
#> 2            0         0         0         0
#> 3            0         0         0         0
#> 4            0         0         0         0
#> 5            0         0         0         0
#> 6            1         1         0         0
```

<sup>Created on 2024-09-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by cebarboza**
Im also merging the changes in tests_latestcode into my branch. I made some changes in `unary_function` as you mentioned before, but I don´t know if that affects your config. 

struct AndJibu : public std ::unary_function<int, void>
struct AndJibu : public std ::__unary_function<int, void>

### CODE REVIEW

**Comment by cebarboza** [comment]
Added a convert_logical and a test to fix issue #28

**Comment by AniekMarkus** [comment]
- saveData fix is great, thanks
- unaryFuncition change:` std::__unary_function` works for me on my laptop=Mac, but not on the server=Linux as I need to use `std::unary_function` there in order to build the package

**Comment by cebarboza** [comment]
> * unaryFuncition change:` std::__unary_function` works for me on my laptop=Mac, but not on the server=Linux as I need to use `std::unary_function` there in order to build the package

Is there any way to define that function accordingly or you don't need it to work on Win?

Also when I integrated your latest changes, the results are different, is that expected?

**Comment by AniekMarkus** [comment]
**Is there any way to define that function accordingly or you don't need it to work on Win?**
For you on Windows ` std::__unary_function ` worked as well right?

It needs to work on all 3 operating systems, but the difference is probably due to different (versions of) C++ compilers that are used as the function ` std::unary_function ` seems to be deprecated at some point: https://en.cppreference.com/w/cpp/utility/functional/unary_function

**Comment by AniekMarkus** [comment]
**Also when I integrated your latest changes, the results are different, is that expected?**
If you mean the changes in the branch [changes_c](https://github.com/mi-erasmusmc/Explore/commits/changes_c) then it is correct that the results might have changed as some corrections were made in the generation of rules!

**Pull request merged**
